# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField()),
                ('url_youtube', models.URLField()),
                ('raiting', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_canciones', to='albumes.Album')),
            ],
        ),
    ]
