# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('biografia', models.TextField()),
                ('foto', models.URLField()),
                ('is_band', models.BooleanField(default=False)),
                ('genero_primario', models.CharField(choices=[('pop', 'Pop'), ('electronica', 'Electrónica'), ('jazz', 'Jazz'), ('clasica', 'Clásica'), ('ranchero', 'Ranchero')], max_length=100)),
                ('albums', models.ManyToManyField(to='albumes.Album')),
            ],
        ),
    ]
