# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='genero_primario',
            field=models.CharField(choices=[('pop', 'Pop'), ('electronica', 'Electrónica'), ('jazz', 'Jazz'), ('clasica', 'Clásica'), ('ranchero', 'Ranchero'), ('rock', 'Rock')], max_length=100),
        ),
    ]
